/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as LabStatesRouteImport } from './routes/lab.states'
import { Route as LabSessionRouteImport } from './routes/lab.session'
import { Route as LabSavedRouteImport } from './routes/lab.saved'
import { Route as LabRefreshRouteImport } from './routes/lab.refresh'
import { Route as LabMutationsRouteImport } from './routes/lab.mutations'
import { Route as LabFaultsRouteImport } from './routes/lab.faults'
import { Route as LabIdRouteImport } from './routes/lab.$id'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedOpportunitiesExamplesRouteImport } from './routes/_authenticated/opportunities.examples'
import { Route as AuthenticatedOpportunitiesIdRouteImport } from './routes/_authenticated/opportunities.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabStatesRoute = LabStatesRouteImport.update({
  id: '/lab/states',
  path: '/lab/states',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSessionRoute = LabSessionRouteImport.update({
  id: '/lab/session',
  path: '/lab/session',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSavedRoute = LabSavedRouteImport.update({
  id: '/lab/saved',
  path: '/lab/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRefreshRoute = LabRefreshRouteImport.update({
  id: '/lab/refresh',
  path: '/lab/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const LabMutationsRoute = LabMutationsRouteImport.update({
  id: '/lab/mutations',
  path: '/lab/mutations',
  getParentRoute: () => rootRouteImport,
} as any)
const LabFaultsRoute = LabFaultsRouteImport.update({
  id: '/lab/faults',
  path: '/lab/faults',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIdRoute = LabIdRouteImport.update({
  id: '/lab/$id',
  path: '/lab/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpportunitiesExamplesRoute =
  AuthenticatedOpportunitiesExamplesRouteImport.update({
    id: '/examples',
    path: '/examples',
    getParentRoute: () => AuthenticatedOpportunitiesRoute,
  } as any)
const AuthenticatedOpportunitiesIdRoute =
  AuthenticatedOpportunitiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedOpportunitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRouteWithChildren
  '/saved': typeof AuthenticatedSavedRoute
  '/lab/$id': typeof LabIdRoute
  '/lab/faults': typeof LabFaultsRoute
  '/lab/mutations': typeof LabMutationsRoute
  '/lab/refresh': typeof LabRefreshRoute
  '/lab/saved': typeof LabSavedRoute
  '/lab/session': typeof LabSessionRoute
  '/lab/states': typeof LabStatesRoute
  '/lab/': typeof LabIndexRoute
  '/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/opportunities/examples': typeof AuthenticatedOpportunitiesExamplesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRouteWithChildren
  '/saved': typeof AuthenticatedSavedRoute
  '/lab/$id': typeof LabIdRoute
  '/lab/faults': typeof LabFaultsRoute
  '/lab/mutations': typeof LabMutationsRoute
  '/lab/refresh': typeof LabRefreshRoute
  '/lab/saved': typeof LabSavedRoute
  '/lab/session': typeof LabSessionRoute
  '/lab/states': typeof LabStatesRoute
  '/lab': typeof LabIndexRoute
  '/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/opportunities/examples': typeof AuthenticatedOpportunitiesExamplesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRouteWithChildren
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/lab/$id': typeof LabIdRoute
  '/lab/faults': typeof LabFaultsRoute
  '/lab/mutations': typeof LabMutationsRoute
  '/lab/refresh': typeof LabRefreshRoute
  '/lab/saved': typeof LabSavedRoute
  '/lab/session': typeof LabSessionRoute
  '/lab/states': typeof LabStatesRoute
  '/lab/': typeof LabIndexRoute
  '/_authenticated/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/_authenticated/opportunities/examples': typeof AuthenticatedOpportunitiesExamplesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/opportunities'
    | '/saved'
    | '/lab/$id'
    | '/lab/faults'
    | '/lab/mutations'
    | '/lab/refresh'
    | '/lab/saved'
    | '/lab/session'
    | '/lab/states'
    | '/lab/'
    | '/opportunities/$id'
    | '/opportunities/examples'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/opportunities'
    | '/saved'
    | '/lab/$id'
    | '/lab/faults'
    | '/lab/mutations'
    | '/lab/refresh'
    | '/lab/saved'
    | '/lab/session'
    | '/lab/states'
    | '/lab'
    | '/opportunities/$id'
    | '/opportunities/examples'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/opportunities'
    | '/_authenticated/saved'
    | '/lab/$id'
    | '/lab/faults'
    | '/lab/mutations'
    | '/lab/refresh'
    | '/lab/saved'
    | '/lab/session'
    | '/lab/states'
    | '/lab/'
    | '/_authenticated/opportunities/$id'
    | '/_authenticated/opportunities/examples'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LabIdRoute: typeof LabIdRoute
  LabFaultsRoute: typeof LabFaultsRoute
  LabMutationsRoute: typeof LabMutationsRoute
  LabRefreshRoute: typeof LabRefreshRoute
  LabSavedRoute: typeof LabSavedRoute
  LabSessionRoute: typeof LabSessionRoute
  LabStatesRoute: typeof LabStatesRoute
  LabIndexRoute: typeof LabIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/states': {
      id: '/lab/states'
      path: '/lab/states'
      fullPath: '/lab/states'
      preLoaderRoute: typeof LabStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/session': {
      id: '/lab/session'
      path: '/lab/session'
      fullPath: '/lab/session'
      preLoaderRoute: typeof LabSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/saved': {
      id: '/lab/saved'
      path: '/lab/saved'
      fullPath: '/lab/saved'
      preLoaderRoute: typeof LabSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/refresh': {
      id: '/lab/refresh'
      path: '/lab/refresh'
      fullPath: '/lab/refresh'
      preLoaderRoute: typeof LabRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/mutations': {
      id: '/lab/mutations'
      path: '/lab/mutations'
      fullPath: '/lab/mutations'
      preLoaderRoute: typeof LabMutationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/faults': {
      id: '/lab/faults'
      path: '/lab/faults'
      fullPath: '/lab/faults'
      preLoaderRoute: typeof LabFaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$id': {
      id: '/lab/$id'
      path: '/lab/$id'
      fullPath: '/lab/$id'
      preLoaderRoute: typeof LabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities/examples': {
      id: '/_authenticated/opportunities/examples'
      path: '/examples'
      fullPath: '/opportunities/examples'
      preLoaderRoute: typeof AuthenticatedOpportunitiesExamplesRouteImport
      parentRoute: typeof AuthenticatedOpportunitiesRoute
    }
    '/_authenticated/opportunities/$id': {
      id: '/_authenticated/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof AuthenticatedOpportunitiesIdRouteImport
      parentRoute: typeof AuthenticatedOpportunitiesRoute
    }
  }
}

interface AuthenticatedOpportunitiesRouteChildren {
  AuthenticatedOpportunitiesIdRoute: typeof AuthenticatedOpportunitiesIdRoute
  AuthenticatedOpportunitiesExamplesRoute: typeof AuthenticatedOpportunitiesExamplesRoute
}

const AuthenticatedOpportunitiesRouteChildren: AuthenticatedOpportunitiesRouteChildren =
  {
    AuthenticatedOpportunitiesIdRoute: AuthenticatedOpportunitiesIdRoute,
    AuthenticatedOpportunitiesExamplesRoute:
      AuthenticatedOpportunitiesExamplesRoute,
  }

const AuthenticatedOpportunitiesRouteWithChildren =
  AuthenticatedOpportunitiesRoute._addFileChildren(
    AuthenticatedOpportunitiesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRouteWithChildren
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRouteWithChildren,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LabIdRoute: LabIdRoute,
  LabFaultsRoute: LabFaultsRoute,
  LabMutationsRoute: LabMutationsRoute,
  LabRefreshRoute: LabRefreshRoute,
  LabSavedRoute: LabSavedRoute,
  LabSessionRoute: LabSessionRoute,
  LabStatesRoute: LabStatesRoute,
  LabIndexRoute: LabIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
